name: Dev Build Image
on:
  push:
    branches:
      - "dev"
    paths:
      - .github/workflows/lks-dev-pipeline.yaml
      - "worker/**"
      - "result/**"
      - "vote/**"

env:
  AWS_REGION: us-east-1
  ENV: "dev"

permissions:
  id-token: write
  contents: read

jobs:
  build_worker:
    name: Build Image Worker Development
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check if worker folder or pipeline file changed
      id: check_worker
      run: |
        git fetch origin ${{ github.event.before }}
        CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^worker/|^.github/workflows/lks-dev-pipeline.yaml' || true)
        if [[ -z "$CHANGED" ]]; then
           echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Update docker version
      if: steps.check_worker.outputs.skip == 'false'
      run: |
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io

    - name: Configure AWS Credentials
      if: steps.check_worker.outputs.skip == 'false'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      if: steps.check_worker.outputs.skip == 'false'
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      if: steps.check_worker.outputs.skip == 'false'
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG --build-arg aws_region=${{ env.AWS_REGION }} --build-arg copy_or_mount="copy" -f worker/Dockerfile ./worker
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG
        echo "worker_image=$ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: End Build
      if: steps.check_worker.outputs.skip == 'false'
      run: echo "Dev Build Worker Success"

  build_result:  
    name: Build Image Result Development
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check if result folder or pipeline file changed
      id: check_result
      run: |
        git fetch origin ${{ github.event.before }}
        CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^result/|^.github/workflows/lks-dev-pipeline.yaml' || true)
        if [[ -z "$CHANGED" ]]; then
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Update docker version
      if: steps.check_result.outputs.skip == 'false'
      run: |
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io

    - name: Configure AWS Credentials
      if: steps.check_result.outputs.skip == 'false'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      if: steps.check_result.outputs.skip == 'false'
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      if: steps.check_result.outputs.skip == 'false'
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        RESULT_IMAGE_TAG: result-${{ env.ENV }}-latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG --build-arg aws_region=${{ env.AWS_REGION }} --build-arg copy_or_mount="copy" -f result/Dockerfile ./result
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG
        echo "result_image=$ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: End Build
      if: steps.check_result.outputs.skip == 'false'
      run: echo "Dev Build Result Success"  

  build_vote:
    name: Build Image Vote Development
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check if vote folder or pipeline file changed
      id: check_vote
      run: |
        git fetch origin ${{ github.event.before }}
        CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^vote/|^.github/workflows/lks-dev-pipeline.yaml' || true)
        if [[ -z "$CHANGED" ]]; then
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Update docker version
      if: steps.check_vote.outputs.skip == 'false'
      run: |
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io

    - name: Configure AWS Credentials
      if: steps.check_vote.outputs.skip == 'false'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      if: steps.check_vote.outputs.skip == 'false'
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      if: steps.check_vote.outputs.skip == 'false'
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        VOTE_IMAGE_TAG: vote-${{ env.ENV }}-latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG --build-arg aws_region=${{ env.AWS_REGION }} --build-arg copy_or_mount="copy" -f vote/Dockerfile ./vote
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG
        echo "vote_image=$ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: End Build
      if: steps.check_vote.outputs.skip == 'false'
      run: echo "Dev Build Vote Success"
  
  pull_image_on_master:
    name: Pull Image on master
    runs-on: [self-hosted, master] 
    steps:
      - name: Update runner's docker Version, as worker module requires it
        run: |
          docker --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Pull Image 
        id: pull-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: voting-app
          WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
          RESULT_IMAGE_TAG: result-${{ env.ENV }}-latest
          VOTE_IMAGE_TAG: vote-${{ env.ENV }}-latest
        # Build docker images for vote module and push it to ECR so that it can be deployed to EKS
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG   
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG
      
      - name: End Pull Image
        run: |
          echo "Success pull image on master"

  pull_image_on_node1:
    name: Pull Image on node1
    runs-on: [self-hosted, node1] 
    steps:
      - name: Update runner's docker Version, as worker module requires it
        run: |
          docker --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Pull Image 
        id: pull-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: voting-app
          WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
          RESULT_IMAGE_TAG: result-${{ env.ENV }}-latest
          VOTE_IMAGE_TAG: vote-${{ env.ENV }}-latest
        # Build docker images for vote module and push it to ECR so that it can be deployed to EKS
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG   
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG
      
      - name: End Pull Image
        run: |
          echo "Success pull image on node1"

  pull_image_on_node2:
    name: Pull Image on node2
    runs-on: [self-hosted, node2] 
    steps:
      - name: Update runner's docker Version, as worker module requires it
        run: |
          docker --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Pull Image 
        id: pull-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: voting-app
          WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
          RESULT_IMAGE_TAG: result-${{ env.ENV }}-latest
          VOTE_IMAGE_TAG: vote-${{ env.ENV }}-latest
        # Build docker images for vote module and push it to ECR so that it can be deployed to EKS
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG   
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG
      
      - name: End Pull Image
        run: |
          echo "Success pull image on node2"