name: Dev Build Image
on:
  push:
    branches:
      - "dev"
    paths:
      - .github/workflows/lks-dev-pipeline.yaml
      - "worker/**"
      - "result/**"
      - "vote/**"

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: lks-voting-image
  ENV: "dev"

permissions:
  id-token: write
  contents: read

jobs:
   
  build_images:
    name: Build application image
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check if worker, result, or vote folder changed
      id: check_changes
      run: |
        git fetch origin ${{ github.event.before }}
        CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

        echo "Changes detected: $CHANGES"
         if echo "$CHANGES" | grep -qE "^worker/|^\.github/workflows/lks-dev-pipeline.yaml"; then
          echo "worker_changed=true" >> $GITHUB_ENV
        fi
         if echo "$CHANGES" | grep -qE "^result/|^\.github/workflows/lks-dev-pipeline.yaml"; then
          echo "result_changed=true" >> $GITHUB_ENV
        fi
         if echo "$CHANGES" | grep -qE "^vote/|^\.github/workflows/lks-dev-pipeline.yaml"; then
          echo "vote_changed=true" >> $GITHUB_ENV
        fi

    - name: Update Docker Version
      if: env.worker_changed == 'true' || env.result_changed == 'true' || env.vote_changed == 'true'
      run: |
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io

    - name: Configure AWS Credentials
      if: env.worker_changed == 'true' || env.result_changed == 'true' || env.vote_changed == 'true'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      if: env.worker_changed == 'true' || env.result_changed == 'true' || env.vote_changed == 'true'
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Worker Image
      if: env.worker_changed == 'true'
      id: build_worker_image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG --build-arg aws_region=${{ env.AWS_REGION }} --build-arg copy_or_mount="copy" -f worker/Dockerfile ./worker
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG
        echo "worker_image=$ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build and Push Result Image
      if: env.result_changed == 'true'
      id: build_result_image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        RESULT_IMAGE_TAG: result-${{ env.ENV }}-latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG --build-arg aws_region=${{ env.AWS_REGION }} --build-arg copy_or_mount="copy" -f result/Dockerfile ./result
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG
        echo "result_image=$ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build and Push Vote Image
      if: env.vote_changed == 'true'
      id: build_vote_image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        VOTE_IMAGE_TAG: vote-${{ env.ENV }}-latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG --build-arg aws_region=${{ env.AWS_REGION }} --build-arg copy_or_mount="copy" -f vote/Dockerfile ./vote
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG
        echo "vote_image=$ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: End Build
      if: env.worker_changed == 'true' || env.result_changed == 'true' || env.vote_changed == 'true'
      run: echo "Dev Build Success"

  pull_image_on_master:
    name: Pull Image on master
    runs-on: [self-hosted, master] 
    needs: build_images
    steps:
      - name: Update runner's docker Version, as worker module requires it
        run: |
          docker --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Pull Image 
        id: pull-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
          RESULT_IMAGE_TAG: result-${{ env.ENV }}-latest
          VOTE_IMAGE_TAG: vote-${{ env.ENV }}-latest
        # Build docker images for vote module and push it to ECR so that it can be deployed to EKS
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG   
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG
      
      - name: End Pull Image
        run: |
          echo "Success pull image on master"

  pull_image_on_node1:
    name: Pull Image on node1
    runs-on: [self-hosted, node1] 
    needs: build_images
    steps:
      - name: Update runner's docker Version, as worker module requires it
        run: |
          docker --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Pull Image 
        id: pull-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
          RESULT_IMAGE_TAG: result-${{ env.ENV }}-latest
          VOTE_IMAGE_TAG: vote-${{ env.ENV }}-latest
        # Build docker images for vote module and push it to ECR so that it can be deployed to EKS
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG   
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG
      
      - name: End Pull Image
        run: |
          echo "Success pull image on node1"

  pull_image_on_node2:
    name: Pull Image on node2
    runs-on: [self-hosted, node2] 
    needs: build_images
    steps:
      - name: Update runner's docker Version, as worker module requires it
        run: |
          docker --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Pull Image 
        id: pull-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          WORKER_IMAGE_TAG: worker-${{ env.ENV }}-latest
          RESULT_IMAGE_TAG: result-${{ env.ENV }}-latest
          VOTE_IMAGE_TAG: vote-${{ env.ENV }}-latest
        # Build docker images for vote module and push it to ECR so that it can be deployed to EKS
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG   
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$RESULT_IMAGE_TAG
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$VOTE_IMAGE_TAG
      
      - name: End Pull Image
        run: |
          echo "Success pull image on node2"